name: backend_shelf
description: An example of using a custom shelf server with jaspr.
version: 0.1.3
publish_to: none

resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  jaspr: ^0.16.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^0.16.3
  lints: ^4.0.0

jaspr:
  mode: server
