name: jaspr_test
description: Testing utilities for jaspr.
version: 0.16.4
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

topics:
  - jaspr
  - web
  - testing

resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  html: ^0.15.0
  http: '>=0.13.0 <2.0.0'
  jaspr: ^0.16.4
  meta: ^1.7.0
  test: ^1.22.0
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
