name: jaspr_tailwind
description: Tailwind integration for jaspr.
version: 0.3.1
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues
documentation: https://docs.page/schultek/jaspr
funding:
  - https://github.com/sponsors/schultek

topics:
  - jaspr
  - web
  - html
  - css

resolution: workspace
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  build: ^2.0.0
  build_modules: ^5.0.4
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^4.0.0
